# Generated by Django 3.0.5 on 2020-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
