# Generated by Django 3.0.5 on 2020-06-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
