# Generated by Django 2.2.6 on 2020-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.CharField(default='exist', max_length=10),
            preserve_default=False,
        ),
    ]
