# Generated by Django 2.2.6 on 2020-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delname', models.CharField(max_length=200)),
                ('delslug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeletedCategories',
        ),
    ]
