# Generated by Django 2.2.6 on 2020-06-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200614_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.DateTimeField(default=2020)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_category', to='api.Categories')),
                ('genre', models.ManyToManyField(to='api.Genre', verbose_name='genres')),
            ],
        ),
    ]
