# Generated by Django 2.2.6 on 2020-06-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200614_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='name',
            new_name='title_name',
        ),
    ]
