# Generated by Django 2.2.6 on 2020-06-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200614_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='title_name',
            new_name='name',
        ),
    ]
